### ISSUE TITLE
Pre-trained embeddings

### ISSUE THREAD

**Issue by mbiesialska** [cambridgeltl/adversarial-postspec#1]
Great work @ducdauge!
Thanks for sharing the code and corresponding resources (vectors and models), they are very helpful. 
I wanted to clarify a few things regarding the [data package](https://drive.google.com/file/d/1e7lhMqmAOSfb8dAAOrf229w67iF5eT3Z/view?usp=sharing) you made available on Google Drive:
1. `prefix` directory doesn't contain **Fasttext vectors** - I guess it is because the size of a [file](https://dl.fbaipublicfiles.com/fasttext/vectors-wiki/wiki.en.vec) is ~6.2GB? If so, can you confirm that the Fasttext Wiki English word vectors file I mentioned here is the one you used in your experiments?
2. **Glove vectors** file in the `prefix` directory appears to not be the same as the Glove vectors [(Common Crawl (42B tokens, 1.9M vocab, uncased, 300d vectors, 1.75 GB download))](http://nlp.stanford.edu/data/glove.42B.300d.zip) shared by the Stanford NLP group. The Stanford vectors have 1,917,494 words while the Glove file in `prefix` has 76,843 words. Also in the Glove file shared by you, words that are at the beginning (`en_waxworks`, `en_manuscripts`, `en_skinful`) are different than the words at the beginning (`,`, `the`, `.`) of the Stanford Glove file, which are ordered based on the frequency. Are these words in your Glove prefix file already specialised? However, the number of words in Glove prefix is different than the number of words in the `ar` directory (after initial specialisation).

I would appreciate if you could point me to the Fasttext and Glove vector files I could use to be able to reproduce the experiments using your tool.
Many thanks!

**Comment by ducdauge** [comment]
Hi @mdbsk, I'm glad that you like the repo, and thanks for your comments!
Regarding your questions:

1. That's correct, the pre-aligned fasttext vectors were sourced from [this page](https://fasttext.cc/docs/en/aligned-vectors.html). I didn't include them in the bundle because they are already freely available online, and to avoid potential proprietary issues.
2. The GloVe vectors, on the other hand, were not downloaded from the latest version on the Stanford page; rather, we used the same vectors employed in previous experiments for semantic specialization, for ease of comparison. The words in _prefix_ are not specialized, just distributional representations. Although their order has been shuffled, they represent the 76,843 most frequent words in English. (As a side note, it may be risky to post-specialize infrequent words because of the lower quality of their representations).

Hope this helps!

**Comment by mbiesialska** [comment]
Thank you @ducdauge for the explanation! I will close the issue now.
